import 'models/car.dart';
import 'models/type.dart';

const List<type> TYPE = const [

  type(id: "c0", name: "Mercedes", image: "images/mercedes.jpg"),
  type(id: "c2", name: "BMW", image: "images/bmw.jpg"),
  type(id: "c3", name: "Skoda", image: "images/skoda.jpg"),
  type(id: "c4", name: "Audi", image: "images/audi.jpg"),
  type(id: "c5", name: "Hyundai", image: "images/hyundai.jpg"),
  type(id: "c6", name: "Kia", image: "images/kia.jpg"),
  type(id: "c7", name: "Land Rover", image: "images/range.jpg"),
  type(id: "c8", name: "Lexus", image: "images/lexus.jpg"),
  type(id: "c9", name: "MG", image: "images/mg.jpg"),
  type(id: "c10", name: "Mini Cooper", image: "images/mini.jpg"),
  type(id: "c11", name: "Mitsubishi", image: "images/mitsubishi.jpg"),
  type(id: "c12", name: "Porsche", image: "images/Porsche.jpg"),
  type(id: "c13", name: "Toyota", image: "images/toyota.jpg"),

];
const List<car> CARS =  [
  /* car(
      id: "m1",
      name: "Mercedes C 180",
      imageUrl: "images/marcedes.jpg",
      price: "2.350.000",
      model :"2023",
      typeNumber: "c1" ),



  car(
      id: "m3",
      name: "Skoda octavia A8",
      imageUrl: "images/scoda.jpg",
      price: "1,850,000",
      model :"2023",
      typeNumber: "c3"),*/

  car(
      id: "m1",
      name: "BMW M X6",
      imageUrl: "images/BMW_X6_M_2023.png",
      price: "6,200,000",
      model :"2023",
      typeNumber: "c2",
      transmission:"Automatic",
      color : "white",
  ),



  car(
      id: "m2",
      name: "Audi A3",
      imageUrl: "images/Audi_A3_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m3",
      name: "Audi A4",
      imageUrl: "images/Audi_A4_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
    ),

  car(
      id: "m4",
      name: "Audi A5",
      imageUrl: "images/Audi_A5_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m5",
      name: "Audi A6",
      imageUrl: "images/Audi_A6_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m6",
      name: "Audi Q2",
      imageUrl: "images/Audi_Q2_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m7",
      name: "Audi Q3",
      imageUrl: "images/Audi_Q3_2023.jpg",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m8",
      name: "Audi Q7",
      imageUrl: "images/Audi_Q7_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m9",
      name: "Audi Q8",
      imageUrl: "images/Audi_Q8_2023.png",
      price: "2.400.000",
      model :"2023",
      typeNumber: "c4",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m10",
      name: "BMW I4",
      imageUrl: "images/BMW_I4_2024.png",
      price: "6,000,000",
      model :"2024",
      typeNumber: "c2",
      transmission:"Automatic",
      color : "white",
  ),

  car(
      id: "m11",
      name: "BMW I5",
      imageUrl: "images/BMW_I5_2024.jpg",
      price: "8,500,000",
      model :"2024",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),

  car(
      id: "m12",
      name: "BMW IX1",
      imageUrl: "images/BMW_IX1_2023.png",
      price: "1,500,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),

  car(
      id: "m13",
      name: "BMW IX",
      imageUrl: "images/BMW_IX_2024.png",
      price: "4,000,000",
      model :"2024",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),

  car(
      id: "m14",
      name: "BMW X2",
      imageUrl: "images/BMW_X2_2023.png",
      price: "1,725,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m15",
      name: "BMW X3",
      imageUrl: "images/BMW_X3_2023.png",
      price: "2,100,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m16",
      name: "BMW X4",
      imageUrl: "images/BMW_X4_2023.jpg",
      price: "3,850,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m17",
      name: "BMW X7",
      imageUrl: "images/BMW_X7_2023.png",
      price: "7,500,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m18",
      name: "BMW 7 Series",
      imageUrl: "images/BMW_7_Series 2023.png",
      price: "9,600,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m19",
      name: "BMW 8 Series",
      imageUrl: "images/BMW_8_Series 2023.jpg",
      price: "11,520,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m20",
      name: "BMW 118",
      imageUrl: "images/BMW_118_2023.png",
      price: "1,700,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m21",
      name: "BMW 218 I",
      imageUrl: "images/BMW_218_I_2023.jpg",
      price: "2,000,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m22",
      name: "BMW 320",
      imageUrl: "images/BMW_320_2023.png",
      price: "1,950,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  // car(
  //     id: "m23",
  //     name: "BMW 320",
  //     imageUrl: "BMW_320_2024.png",
  //     price: "3,000,000",
  //     model :"2024",
  //     typeNumber: "c2"),

  car(
      id: "m24",
      name: "BMW 420",
      imageUrl: "images/BMW_420_2023.jpg",
      price: "5,000,000",
      model :"2023",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m25",
      name: "BMW 520",
      imageUrl: "images/BMW_520_2024.jpg",
      price: "7,200,000",
      model :"2024",
    typeNumber: "c2",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m26",
      name: "Hyundai Accent HCI",
      imageUrl: "images/Hyundai_Accent_HCI_2022_New_Generation.jpg",
      price: "1.250.000",
      model :"2022",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m27",
      name: "Hyundai Accent RB",
      imageUrl: "images/Hyundai_Accent_RB_2023.png",
      price: "830,000",
      model :"2023",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m28",
      name: "Hyundai Bayonne",
      imageUrl: "images/Hyundai_Bayonne_2022.png",
      price: "700,000",
      model :"2022",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m29",
      name: "Hyundai Creta SUV2",
      imageUrl: "images/Hyundai_Creta_SUV2_2022.jpg",
      price: "1,500,000",
      model :"2022",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m30",
      name: "Hyundai CN7",
      imageUrl: "images/Hyundai_Elantra_CN7_2024.png",
      price: "800,000",
      model :"2024",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m31",
      name: "Hyundai I20",
      imageUrl: "images/Hyundai_I20_2022.png",
      price: "700,000",
      model :"2022",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m32",
      name: "Hyundai l10",
      imageUrl: "images/Hyundai_l10_2022.png",
      price: "500,000",
      model :"2022",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m33",
      name: "Hyundai Tuscon",
      imageUrl: "images/Hyundai_Tucson_2022_New_Generation.png",
      price: "1.000,000",
      model :"2022",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m34",
      name: "Hyundai Tuscon",
      imageUrl: "images/Hyundai_Tucson_2023.png",
      price: "1.200.000",
      model :"2023",
    typeNumber: "c5",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m35",
      name: "Kia Exceed",
      imageUrl: "images/Kia_Exceed_2022.jpg",
      price: "770.000",
      model :"2022",
    typeNumber: "c6",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m36",
      name: "Kia Sportage",
      imageUrl: "images/Kia_Sportage_2023.jpg",
      price: "1.750.000",
      model :"2023",
    typeNumber: "c6",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m37",
      name: "LR Defender",
      imageUrl: "images/Land_Rover_Defender_2021.jpg",
      price: "1.600.000",
      model :"2021",
    typeNumber: "c7",
    transmission:"Automatic",
    color : "white",
  ),

  car(
      id: "m38",
      name: "LR Discovery sport",
      imageUrl: "images/Land_Rover_Discovery_Sport_2021.png",
      price: "3.200.000",
      model :"2021",
    typeNumber: "c7",
    transmission:"Automatic",
    color : "white",
  ),

  car(
      id: "m39",
      name: "LR Evoque",
      imageUrl: "images/Land_Rover_Range_Rover_Evoque_2021.jpg",
      price: "4.500.000",
      model :"2021",
    typeNumber: "c7",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m40",
      name: "Land Rover Vogue",
      imageUrl: "images/Land_Rover_Range_Rover_Vogue_2020.png",
      price: "4.750.000",
      model :"2020",
    typeNumber: "c7",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m41",
      name: "Lexus ES 350",
      imageUrl: "images/Lexus_ES_350_2020.png",
      price: "2.500.000",
      model :"2020",
    typeNumber: "c8",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m42",
      name: "Lexus LS 500",
      imageUrl: "images/Lexus_LS_500_2020.png",
      price: "6.000.000",
      model :"2020",
    typeNumber: "c8",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m43",
      name: "Lexus RX",
      imageUrl: "images/Lexus_Rx_2020.png",
      price: "2.600.000",
      model :"2020",
    typeNumber: "c8",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m44",
      name: "Mercedes AMG GT",
      imageUrl: "images/Mercedes_AMG_GT_2022.jpg",
      price: "5.350.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m45",
      name: "Mercedes C 200",
      imageUrl: "images/Mercedes_C_200_2023.jpg",
      price: "2.000.000",
      model :"2023",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m46",
      name: "Mercedes CLA 200",
      imageUrl: "images/Mercedes_CLA_200_2022.png",
      price: "1.600.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m47",
      name: "Mercedes E 53 AMG",
      imageUrl: "images/Mercedes_E_53_AMG 2022.jpg",
      price: "5.100.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m48",
      name: "Mercedes G Class",
      imageUrl: "images/Mercedes_G_Class 2022.png",
      price: "4.600.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m49",
      name: "Mercedes GLA",
      imageUrl: "images/Mercedes_GLA_2022.png",
      price: "1.600.000",
      model :"2023",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m50",
      name: "Mercedes GLC 200",
      imageUrl: "images/Mercedes_GLC_200_AMG_2023.png",
      price: "1.600.000",
      model :"2023",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m51",
      name: "Mercedes GLC 300",
      imageUrl: "images/Mercedes_GLC_300_2022.jpg",
      price: "3.600.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m52",
      name: "Mercedes GLE",
      imageUrl: "images/Mercedes_GLE_2022.png",
      price: "2.400.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m53",
      name: "Mercedes Maybach",
      imageUrl: "images/Mercedes_Maybach_2022.png",
      price: "10.000.000",
      model :"2022",
    typeNumber: "c0",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m54",
      name: "MG 5",
      imageUrl: "images/MG_5_2023.png",
      price: "1.000.000",
      model :"2023",
    typeNumber: "c9",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m55",
      name: "MG 6",
      imageUrl: "images/MG_6_2023.png",
      price: "1.250.000",
      model :"2023",
    typeNumber: "c9",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m56",
      name: "MG RX5 PLUS",
      imageUrl: "images/MG_RX5_Plus_2023.png",
      price: "1.100.000",
      model :"2023",
    typeNumber: "c9",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m57",
      name: "MG ZS",
      imageUrl: "images/MG_ZS_2022.png",
      price: "1.100.000",
      model :"2022",
    typeNumber: "c9",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m58",
      name: "Mini Cooper",
      imageUrl: "images/Mini_Cooper_2023.png",
      price: "1.500.000",
      model :"2023",
    typeNumber: "c10",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m59",
      name: "Mini Cooper s",
      imageUrl: "images/Mini_Cooper_S_2024.png",
      price: "1.800.000",
      model :"2024",
    typeNumber: "c10",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m60",
      name: "Minu Countryman",
      imageUrl: "images/Mini_Countryman_2024_New_Generation.jpg",
      price: "1.500.000",
      model :"2024",
    typeNumber: "c10",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m61",
      name: "Mitsubishi Attrage",
      imageUrl: "images/Mitsubishi_Attrage_2024.png",
      price: "450.000",
      model :"2024",
    typeNumber: "c11",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m62",
      name: "Mitsubishi Eclipse",
      imageUrl: "images/Mitsubishi_Eclipse_Cross_2023.png",
      price: "1.400.000",
      model :"2023",
    typeNumber: "c11",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m63",
      name: "Mitsubishi Mirage",
      imageUrl: "images/Mitsubishi_Mirage_2024.png",
      price: "800.000",
      model :"2024",
    typeNumber: "c11",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m64",
      name: "Mitsubishi Xpander",
      imageUrl: "images/Mitsubishi_Xpander_2023.png",
      price: "950.000",
      model :"2023",
    typeNumber: "c11",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m65",
      name: "Porsche 718",
      imageUrl: "images/Porsche_718_2023.jpg",
      price: "3.550.000",
      model :"2023",
    typeNumber: "c12",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m66",
      name: "Porsche 911",
      imageUrl: "images/Porsche_911_2021.jpg",
      price: "5.550.000",
      model :"2021",
    typeNumber: "c12",
    transmission:"Automatic",
    color : "white",
  ),
  // car(
  //     id: "m67",
  //     name: "Porsche 911",
  //     imageUrl: "images/Porsche_911_2023.jpg",
  //     price: "6.550.000",
  //     model :"2023",
  //     typeNumber: "c12"),

  car(
      id: "m68",
      name: "Porsche Boxter S",
      imageUrl: "images/Porsche_Boxster_S_2020.png",
      price: "950.000",
      model :"2020",
    typeNumber: "c12",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m69",
      name: "Porsche Cayman S",
      imageUrl: "images/Porsche_Cayman_S_2020.jpg",
      price: "1.750.000",
      model :"2020",
    typeNumber: "c12",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m70",
      name: "Porsche Panamera",
      imageUrl: "images/Porsche_Panamera_2023.jpg",
      price: "5.500.000",
      model :"2023",
    typeNumber: "c12",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m71",
      name: "Skoda Kamiq",
      imageUrl: "images/Skoda_Kamiq_2023.png",
      price: "5.100.000",
      model :"2023",
    typeNumber: "c3",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m72",
      name: "Skoda Kodiaq",
      imageUrl: "images/Skoda_Kodiaq_2024.png",
      price: "3.000.000",
      model :"2024",
    typeNumber: "c3",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m73",
      name: "Skoda Octavia",
      imageUrl: "images/Skoda_Octavia_A8_2023.jpg",
      price: "2.000.000",
      model :"2023",
    typeNumber: "c3",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m74",
      name: "Skoda Superb",
      imageUrl: "images/Skoda_Superb_2023.jpg",
      price: "1.550.000",
      model :"2023",
    typeNumber: "c3",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m75",
      name: "Skoda Fabia",
      imageUrl: "images/Skoda_Fabia_2023.jpg",
      price: "750.000",
      model :"2023",
    typeNumber: "c3",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m76",
      name: "Toyota Belta",
      imageUrl: "images/Toyota_Belta_2022.png",
      price: "405.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m77",
      name: "Toyota C HR",
      imageUrl: "images/Toyota_C-HR_2022.jpg",
      price: "500.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m78",
      name: "Toyota camry",
      imageUrl: "images/Toyota_camry_2022.png",
      price: "3.000.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m79",
      name: "Toyota Corolla",
      imageUrl: "images/Toyota_Corolla_2022.png",
      price: "750.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m80",
      name: "Toyota Corolla",
      imageUrl: "images/Toyota_Corolla_2023.png",
      price: "950.000",
      model :"2023",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m81",
      name: "Toyota Fortuner",
      imageUrl: "images/Toyota_Fortuner_2024.jpg",
      price: "4.100.000",
      model :"2024",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m82",
      name: "Toyota Land Cruiser",
      imageUrl: "images/Toyota_Land_Cruiser_2022.png",
      price: "4.000.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m83",
      name: "Toyota Rumion",
      imageUrl: "images/Toyota_Rumion_2022.png",
      price: "750.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),
  car(
      id: "m84",
      name: "Toyota Yaris",
      imageUrl: "images/Toyota_Yaris_2022.jpeg",
      price: "400.000",
      model :"2022",
    typeNumber: "c13",
    transmission:"Automatic",
    color : "white",
  ),











];